"""tasks

Revision ID: 064fb60958a1
Revises: 0f57d8670111
Create Date: 2024-06-13 23:45:00.008223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064fb60958a1'
down_revision = '0f57d8670111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reading', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_name'))

    op.drop_table('reading')
    # ### end Alembic commands ###
