"""Change name

Revision ID: 0f57d8670111
Revises: 854b51d02838
Create Date: 2024-06-13 21:00:44.114211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f57d8670111'
down_revision = '854b51d02838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speed_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fan_id', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('change_reason', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['fan_id'], ['fan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('speed_change', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_speed_change_change_reason'), ['change_reason'], unique=False)
        batch_op.create_index(batch_op.f('ix_speed_change_fan_id'), ['fan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_speed_change_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('speed_reading', schema=None) as batch_op:
        batch_op.drop_index('ix_speed_reading_change_reason')
        batch_op.drop_index('ix_speed_reading_fan_id')
        batch_op.drop_index('ix_speed_reading_timestamp')

    op.drop_table('speed_reading')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speed_reading',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fan_id', sa.INTEGER(), nullable=False),
    sa.Column('speed', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('change_reason', sa.VARCHAR(length=64), nullable=False),
    sa.ForeignKeyConstraint(['fan_id'], ['fan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('speed_reading', schema=None) as batch_op:
        batch_op.create_index('ix_speed_reading_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_speed_reading_fan_id', ['fan_id'], unique=False)
        batch_op.create_index('ix_speed_reading_change_reason', ['change_reason'], unique=False)

    with op.batch_alter_table('speed_change', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_speed_change_timestamp'))
        batch_op.drop_index(batch_op.f('ix_speed_change_fan_id'))
        batch_op.drop_index(batch_op.f('ix_speed_change_change_reason'))

    op.drop_table('speed_change')
    # ### end Alembic commands ###
