"""fan update

Revision ID: 3c3f5bb1ffca
Revises: 1e2013ebcb45
Create Date: 2024-06-26 03:40:17.202572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c3f5bb1ffca'
down_revision = '1e2013ebcb45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pwm', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('has_switch', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fan', schema=None) as batch_op:
        batch_op.drop_column('has_switch')
        batch_op.drop_column('is_pwm')

    # ### end Alembic commands ###
