"""fans update

Revision ID: a68217b4d473
Revises: 3c3f5bb1ffca
Create Date: 2024-06-26 22:28:29.535008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a68217b4d473'
down_revision = '3c3f5bb1ffca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('switch_pin', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('has_pwm', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('pwm_pin', sa.Integer(), nullable=False))
        batch_op.drop_column('is_pwm')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pwm', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('pwm_pin')
        batch_op.drop_column('has_pwm')
        batch_op.drop_column('switch_pin')

    # ### end Alembic commands ###
