"""init

Revision ID: b07ad1a50011
Revises: 
Create Date: 2024-07-06 19:28:55.234967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07ad1a50011'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fan',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('has_swtch', sa.Boolean(), nullable=False),
    sa.Column('swtch_pin', sa.Integer(), nullable=False),
    sa.Column('has_pwm', sa.Boolean(), nullable=False),
    sa.Column('pwm_pin', sa.Integer(), nullable=False),
    sa.Column('swtch', sa.Boolean(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sensor',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.String(), nullable=False),
    sa.Column('temp', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reading', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_sensor_id'), ['sensor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_timestamp'), ['timestamp'], unique=False)

    op.create_table('speed_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('change_reason', sa.String(length=64), nullable=False),
    sa.Column('fan_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['fan_id'], ['fan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('speed_change', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_speed_change_change_reason'), ['change_reason'], unique=False)
        batch_op.create_index(batch_op.f('ix_speed_change_fan_id'), ['fan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_speed_change_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('speed_change', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_speed_change_timestamp'))
        batch_op.drop_index(batch_op.f('ix_speed_change_fan_id'))
        batch_op.drop_index(batch_op.f('ix_speed_change_change_reason'))

    op.drop_table('speed_change')
    with op.batch_alter_table('reading', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_timestamp'))
        batch_op.drop_index(batch_op.f('ix_reading_sensor_id'))

    op.drop_table('reading')
    op.drop_table('sensor')
    op.drop_table('fan')
    # ### end Alembic commands ###
