"""is_on

Revision ID: fd5fa2ca2e43
Revises: 213faa10c2f1
Create Date: 2024-06-20 07:07:11.880117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5fa2ca2e43'
down_revision = '213faa10c2f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_on', sa.Boolean(), nullable=False))
        batch_op.drop_column('switch')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('switch', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('is_on')

    # ### end Alembic commands ###
